# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [12]:
import numpy as np   #To execute any line or many lines (statements) press shift+enter

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [19]:
lst #No need of print() to output the values)

[1, 2, 3]

In [20]:
arr = np.array(lst) #np.array() is a method to make a python list into Numpy Array

In [21]:
arr

array([1, 2, 3])

In [22]:
matrix = [[1,2,3],[4,5,6],[7,8,9]] #List of Lists

In [23]:
matrix #lets try with Numpy

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
mat= np.array(matrix)

In [26]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.array(matrix) #If we execute any line without variable ..the output shows Immediately

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [31]:
np.arange(0,10) #start=0 ,end=10 -->that means upto 9 . np.arange(start,end) makes an array from start to upto end

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(0,15,2)#start=0,end=15 (upto 15), stepsize=2 means difference of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14])

### zeros and ones

Generate arrays of zeros or ones

In [35]:
np.zeros(3) # makes an array with number of zeroes passed in the ()

array([0., 0., 0.])

In [37]:
np.zeros((2,3)) #makes array with zeros in 2-rows and 3-columns 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.ones(5) #makes array with 1's with aarguement in ()

array([1., 1., 1., 1., 1.])

In [41]:
np.ones((5,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [45]:
np.linspace(1,2,4) #start=1 end =2 ...makes 4 elements in array evenly

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [47]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

## eye

Creates an identity matrix

In [50]:
np.eye(5) #sq matrix 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [54]:
np.random.rand(5) # random numbers from 0 to 1 with number passed in argument

array([0.53410031, 0.88580554, 0.80102177, 0.8046313 , 0.95211178])

In [55]:
np.random.rand(3,3)

array([[0.97865283, 0.02080529, 0.73020727],
       [0.48240326, 0.38428757, 0.45974433],
       [0.69415302, 0.84436247, 0.0330083 ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [58]:
np.random.randn(5)

array([-2.61453023, -1.3831986 , -1.03503114, -0.13952688,  1.20673733])

In [60]:
np.random.randn(5,5)

array([[-0.35020445,  0.18285446, -0.73404354, -0.80374872, -0.33729294],
       [ 0.34768158, -0.34675199, -0.00906332, -1.43298451, -0.75779663],
       [ 0.56090419, -0.26983158, -0.75889602, -0.0406953 ,  1.391589  ],
       [-0.52571472,  0.78592669,  0.78840107,  1.47639762, -0.16086209],
       [-0.06696445, -0.63784433, -0.74761929,  1.21903609, -0.8781499 ]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [62]:
np.random.randint(1,100)

71

In [64]:
np.random.randint(1,100,20) #start=1 , end=100 , outputs 20 elements

array([53, 84, 81, 69, 10, 49, 69, 85, 65, 50,  9, 74,  2, 58, 93, 41, 56,
       45, 63, 67])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [65]:
arr = np.arange(25)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [68]:
randarr = np.random.randint(0,50,10)

In [69]:
randarr

array([ 2, 30,  6, 49, 37, 14, 39, 42, 26, 47])

## Reshape
Returns an array containing the same data with a new shape.

In [127]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
arr.reshape(5,5) #rows=5 , cols=5 ,then elements should be 25 in the array you try to reshape ..otherwise it outputs error

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [119]:
randarr

array([ 2, 30,  6, 49, 37, 14, 39, 42, 26, 47])

In [120]:
randarr.max()

49

In [121]:
randarr.min()

2

In [122]:
randarr.argmax() #this method outputs index value of maximum number

3

In [123]:
randarr.argmin() #this method outputs index value of minimum number

0

## Shape

Shape is an attribute that arrays have (not a method):

In [145]:
arr.shape

(25,)

In [146]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [147]:
arr = arr.reshape(5,5)

In [148]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [149]:
arr.shape

(5, 5)

In [151]:
arr=arr.reshape(25,1)

In [152]:
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### dtype

You can also grab the data type of the object in the array:

arr.dtype

# Another Method For Importing

In [161]:
from numpy.random import randint

In [166]:
randint(5,100,20)

array([42, 92, 26, 38, 71, 76, 47, 20, 45, 66, 26, 27, 33, 24, 96, 40, 18,
       18, 70, 67])

# Great Job!